// Program ROM, GENERATED by tools/gen_rom.py from programs/manifest.txt. Do not edit;
// run `make rom` after changing a program or the manifest, `make rom-check` guards it.
//
// One ROM per slot: word = program[sel][addr], words = its length. Slot 0 and every
// slot not listed read 0 and 0, so the core halts. Programs keep their own addresses.
//
// slot  words  program
//    1     11  uart_tx_0x55.asm
//    2     11  uart_tx_pull.asm
//    3     12  uart_tx_loop.asm
//    4     12  uart_rx.asm
//    5     21  spi_tx_lsb.asm
//    6     21  spi_tx_msb.asm
//    7     22  spi_duplex_lsb.asm
//    8     22  spi_duplex_msb.asm
//    9     34  i2c_write.asm
//   10     45  i2c_write_stretch.asm
//   11     64  i2c_write_addr_data.asm

module rom (
    input      [3:0]  sel,
    input      [7:0]  addr,
    output reg [15:0] word,
    output reg [8:0]  words
);

    always @* begin
        case ({sel, addr})
            // slot 1: uart_tx_0x55.asm
            12'h100: word = 16'h0790;  //   0  SET 0, 1 [7]
            12'h101: word = 16'h0780;  //   1  SET 0, 0 [7]
            12'h102: word = 16'h0790;  //   2  SET 0, 1 [7]
            12'h103: word = 16'h0780;  //   3  SET 0, 0 [7]
            12'h104: word = 16'h0790;  //   4  SET 0, 1 [7]
            12'h105: word = 16'h0780;  //   5  SET 0, 0 [7]
            12'h106: word = 16'h0790;  //   6  SET 0, 1 [7]
            12'h107: word = 16'h0780;  //   7  SET 0, 0 [7]
            12'h108: word = 16'h0790;  //   8  SET 0, 1 [7]
            12'h109: word = 16'h0780;  //   9  SET 0, 0 [7]
            12'h10a: word = 16'h0790;  //  10  SET 0, 1 [7]
            // slot 2: uart_tx_pull.asm
            12'h200: word = 16'h0790;  //   0  SET 0, 1 [7]
            12'h201: word = 16'h4780;  //   1  PULL 0, 0 [7]
            12'h202: word = 16'h2700;  //   2  SHIFT_OUT  [7]
            12'h203: word = 16'h2700;  //   3  SHIFT_OUT  [7]
            12'h204: word = 16'h2700;  //   4  SHIFT_OUT  [7]
            12'h205: word = 16'h2700;  //   5  SHIFT_OUT  [7]
            12'h206: word = 16'h2700;  //   6  SHIFT_OUT  [7]
            12'h207: word = 16'h2700;  //   7  SHIFT_OUT  [7]
            12'h208: word = 16'h2700;  //   8  SHIFT_OUT  [7]
            12'h209: word = 16'h2700;  //   9  SHIFT_OUT  [7]
            12'h20a: word = 16'h0790;  //  10  SET 0, 1 [7]
            // slot 3: uart_tx_loop.asm
            12'h300: word = 16'h0090;  //   0  SET 0, 1
            12'h301: word = 16'h4780;  //   1  PULL 0, 0 [7]
            12'h302: word = 16'h2700;  //   2  SHIFT_OUT  [7]
            12'h303: word = 16'h2700;  //   3  SHIFT_OUT  [7]
            12'h304: word = 16'h2700;  //   4  SHIFT_OUT  [7]
            12'h305: word = 16'h2700;  //   5  SHIFT_OUT  [7]
            12'h306: word = 16'h2700;  //   6  SHIFT_OUT  [7]
            12'h307: word = 16'h2700;  //   7  SHIFT_OUT  [7]
            12'h308: word = 16'h2700;  //   8  SHIFT_OUT  [7]
            12'h309: word = 16'h2700;  //   9  SHIFT_OUT  [7]
            12'h30a: word = 16'h0790;  //  10  SET 0, 1 [7]
            12'h30b: word = 16'h6001;  //  11  JMP 1
            // slot 4: uart_rx.asm
            12'h400: word = 16'h8005;  //   0  CONFIG open_drain01, 1
            12'h401: word = 16'hab00;  //   1  WAIT 0, 0 [11]
            12'h402: word = 16'h2702;  //   2  SHIFT_IN 0 [7]
            12'h403: word = 16'h2702;  //   3  SHIFT_IN 0 [7]
            12'h404: word = 16'h2702;  //   4  SHIFT_IN 0 [7]
            12'h405: word = 16'h2702;  //   5  SHIFT_IN 0 [7]
            12'h406: word = 16'h2702;  //   6  SHIFT_IN 0 [7]
            12'h407: word = 16'h2702;  //   7  SHIFT_IN 0 [7]
            12'h408: word = 16'h2702;  //   8  SHIFT_IN 0 [7]
            12'h409: word = 16'h2702;  //   9  SHIFT_IN 0 [7]
            12'h40a: word = 16'h4201;  //  10  PUSH  [2]
            12'h40b: word = 16'h6001;  //  11  JMP 1
            // slot 5: spi_tx_lsb.asm
            12'h500: word = 16'h8000;  //   0  CONFIG shift_dir, 0
            12'h501: word = 16'h00a0;  //   1  SET 1, 0
            12'h502: word = 16'h43c0;  //   2  PULL 2, 0 [3]
            12'h503: word = 16'h23a0;  //   3  SHIFT_OUT 1, 0 [3]
            12'h504: word = 16'h03b0;  //   4  SET 1, 1 [3]
            12'h505: word = 16'h23a0;  //   5  SHIFT_OUT 1, 0 [3]
            12'h506: word = 16'h03b0;  //   6  SET 1, 1 [3]
            12'h507: word = 16'h23a0;  //   7  SHIFT_OUT 1, 0 [3]
            12'h508: word = 16'h03b0;  //   8  SET 1, 1 [3]
            12'h509: word = 16'h23a0;  //   9  SHIFT_OUT 1, 0 [3]
            12'h50a: word = 16'h03b0;  //  10  SET 1, 1 [3]
            12'h50b: word = 16'h23a0;  //  11  SHIFT_OUT 1, 0 [3]
            12'h50c: word = 16'h03b0;  //  12  SET 1, 1 [3]
            12'h50d: word = 16'h23a0;  //  13  SHIFT_OUT 1, 0 [3]
            12'h50e: word = 16'h03b0;  //  14  SET 1, 1 [3]
            12'h50f: word = 16'h23a0;  //  15  SHIFT_OUT 1, 0 [3]
            12'h510: word = 16'h03b0;  //  16  SET 1, 1 [3]
            12'h511: word = 16'h23a0;  //  17  SHIFT_OUT 1, 0 [3]
            12'h512: word = 16'h03b0;  //  18  SET 1, 1 [3]
            12'h513: word = 16'h03a0;  //  19  SET 1, 0 [3]
            12'h514: word = 16'h00d0;  //  20  SET 2, 1
            // slot 6: spi_tx_msb.asm
            12'h600: word = 16'h8001;  //   0  CONFIG shift_dir, 1
            12'h601: word = 16'h00a0;  //   1  SET 1, 0
            12'h602: word = 16'h43c0;  //   2  PULL 2, 0 [3]
            12'h603: word = 16'h23a0;  //   3  SHIFT_OUT 1, 0 [3]
            12'h604: word = 16'h03b0;  //   4  SET 1, 1 [3]
            12'h605: word = 16'h23a0;  //   5  SHIFT_OUT 1, 0 [3]
            12'h606: word = 16'h03b0;  //   6  SET 1, 1 [3]
            12'h607: word = 16'h23a0;  //   7  SHIFT_OUT 1, 0 [3]
            12'h608: word = 16'h03b0;  //   8  SET 1, 1 [3]
            12'h609: word = 16'h23a0;  //   9  SHIFT_OUT 1, 0 [3]
            12'h60a: word = 16'h03b0;  //  10  SET 1, 1 [3]
            12'h60b: word = 16'h23a0;  //  11  SHIFT_OUT 1, 0 [3]
            12'h60c: word = 16'h03b0;  //  12  SET 1, 1 [3]
            12'h60d: word = 16'h23a0;  //  13  SHIFT_OUT 1, 0 [3]
            12'h60e: word = 16'h03b0;  //  14  SET 1, 1 [3]
            12'h60f: word = 16'h23a0;  //  15  SHIFT_OUT 1, 0 [3]
            12'h610: word = 16'h03b0;  //  16  SET 1, 1 [3]
            12'h611: word = 16'h23a0;  //  17  SHIFT_OUT 1, 0 [3]
            12'h612: word = 16'h03b0;  //  18  SET 1, 1 [3]
            12'h613: word = 16'h03a0;  //  19  SET 1, 0 [3]
            12'h614: word = 16'h00d0;  //  20  SET 2, 1
            // slot 7: spi_duplex_lsb.asm
            12'h700: word = 16'h800a;  //   0  CONFIG open_drain23, 2
            12'h701: word = 16'h8000;  //   1  CONFIG shift_dir, 0
            12'h702: word = 16'h00a0;  //   2  SET 1, 0
            12'h703: word = 16'h43c0;  //   3  PULL 2, 0 [3]
            12'h704: word = 16'h23a0;  //   4  SHIFT_OUT 1, 0 [3]
            12'h705: word = 16'h23be;  //   5  SHIFT_IN 3, 1, 1 [3]
            12'h706: word = 16'h23a0;  //   6  SHIFT_OUT 1, 0 [3]
            12'h707: word = 16'h23be;  //   7  SHIFT_IN 3, 1, 1 [3]
            12'h708: word = 16'h23a0;  //   8  SHIFT_OUT 1, 0 [3]
            12'h709: word = 16'h23be;  //   9  SHIFT_IN 3, 1, 1 [3]
            12'h70a: word = 16'h23a0;  //  10  SHIFT_OUT 1, 0 [3]
            12'h70b: word = 16'h23be;  //  11  SHIFT_IN 3, 1, 1 [3]
            12'h70c: word = 16'h23a0;  //  12  SHIFT_OUT 1, 0 [3]
            12'h70d: word = 16'h23be;  //  13  SHIFT_IN 3, 1, 1 [3]
            12'h70e: word = 16'h23a0;  //  14  SHIFT_OUT 1, 0 [3]
            12'h70f: word = 16'h23be;  //  15  SHIFT_IN 3, 1, 1 [3]
            12'h710: word = 16'h23a0;  //  16  SHIFT_OUT 1, 0 [3]
            12'h711: word = 16'h23be;  //  17  SHIFT_IN 3, 1, 1 [3]
            12'h712: word = 16'h23a0;  //  18  SHIFT_OUT 1, 0 [3]
            12'h713: word = 16'h23be;  //  19  SHIFT_IN 3, 1, 1 [3]
            12'h714: word = 16'h03a0;  //  20  SET 1, 0 [3]
            12'h715: word = 16'h40d1;  //  21  PUSH 2, 1
            // slot 8: spi_duplex_msb.asm
            12'h800: word = 16'h800a;  //   0  CONFIG open_drain23, 2
            12'h801: word = 16'h8001;  //   1  CONFIG shift_dir, 1
            12'h802: word = 16'h00a0;  //   2  SET 1, 0
            12'h803: word = 16'h43c0;  //   3  PULL 2, 0 [3]
            12'h804: word = 16'h23a0;  //   4  SHIFT_OUT 1, 0 [3]
            12'h805: word = 16'h23be;  //   5  SHIFT_IN 3, 1, 1 [3]
            12'h806: word = 16'h23a0;  //   6  SHIFT_OUT 1, 0 [3]
            12'h807: word = 16'h23be;  //   7  SHIFT_IN 3, 1, 1 [3]
            12'h808: word = 16'h23a0;  //   8  SHIFT_OUT 1, 0 [3]
            12'h809: word = 16'h23be;  //   9  SHIFT_IN 3, 1, 1 [3]
            12'h80a: word = 16'h23a0;  //  10  SHIFT_OUT 1, 0 [3]
            12'h80b: word = 16'h23be;  //  11  SHIFT_IN 3, 1, 1 [3]
            12'h80c: word = 16'h23a0;  //  12  SHIFT_OUT 1, 0 [3]
            12'h80d: word = 16'h23be;  //  13  SHIFT_IN 3, 1, 1 [3]
            12'h80e: word = 16'h23a0;  //  14  SHIFT_OUT 1, 0 [3]
            12'h80f: word = 16'h23be;  //  15  SHIFT_IN 3, 1, 1 [3]
            12'h810: word = 16'h23a0;  //  16  SHIFT_OUT 1, 0 [3]
            12'h811: word = 16'h23be;  //  17  SHIFT_IN 3, 1, 1 [3]
            12'h812: word = 16'h23a0;  //  18  SHIFT_OUT 1, 0 [3]
            12'h813: word = 16'h23be;  //  19  SHIFT_IN 3, 1, 1 [3]
            12'h814: word = 16'h03a0;  //  20  SET 1, 0 [3]
            12'h815: word = 16'h40d1;  //  21  PUSH 2, 1
            // slot 9: i2c_write.asm
            12'h900: word = 16'h8007;  //   0  CONFIG open_drain01, 3
            12'h901: word = 16'h8001;  //   1  CONFIG shift_dir, 1
            12'h902: word = 16'h4380;  //   2  PULL 0, 0 [3]
            12'h903: word = 16'h01a0;  //   3  SET 1, 0 [1]
            12'h904: word = 16'h2100;  //   4  SHIFT_OUT  [1]
            12'h905: word = 16'h03b0;  //   5  SET 1, 1 [3]
            12'h906: word = 16'h01a0;  //   6  SET 1, 0 [1]
            12'h907: word = 16'h2100;  //   7  SHIFT_OUT  [1]
            12'h908: word = 16'h03b0;  //   8  SET 1, 1 [3]
            12'h909: word = 16'h01a0;  //   9  SET 1, 0 [1]
            12'h90a: word = 16'h2100;  //  10  SHIFT_OUT  [1]
            12'h90b: word = 16'h03b0;  //  11  SET 1, 1 [3]
            12'h90c: word = 16'h01a0;  //  12  SET 1, 0 [1]
            12'h90d: word = 16'h2100;  //  13  SHIFT_OUT  [1]
            12'h90e: word = 16'h03b0;  //  14  SET 1, 1 [3]
            12'h90f: word = 16'h01a0;  //  15  SET 1, 0 [1]
            12'h910: word = 16'h2100;  //  16  SHIFT_OUT  [1]
            12'h911: word = 16'h03b0;  //  17  SET 1, 1 [3]
            12'h912: word = 16'h01a0;  //  18  SET 1, 0 [1]
            12'h913: word = 16'h2100;  //  19  SHIFT_OUT  [1]
            12'h914: word = 16'h03b0;  //  20  SET 1, 1 [3]
            12'h915: word = 16'h01a0;  //  21  SET 1, 0 [1]
            12'h916: word = 16'h2100;  //  22  SHIFT_OUT  [1]
            12'h917: word = 16'h03b0;  //  23  SET 1, 1 [3]
            12'h918: word = 16'h01a0;  //  24  SET 1, 0 [1]
            12'h919: word = 16'h2100;  //  25  SHIFT_OUT  [1]
            12'h91a: word = 16'h03b0;  //  26  SET 1, 1 [3]
            12'h91b: word = 16'h01a0;  //  27  SET 1, 0 [1]
            12'h91c: word = 16'h0190;  //  28  SET 0, 1 [1]
            12'h91d: word = 16'h23b2;  //  29  SHIFT_IN 0, 1, 1 [3]
            12'h91e: word = 16'h41a1;  //  30  PUSH 1, 0 [1]
            12'h91f: word = 16'h0180;  //  31  SET 0, 0 [1]
            12'h920: word = 16'h01b0;  //  32  SET 1, 1 [1]
            12'h921: word = 16'h0390;  //  33  SET 0, 1 [3]
            // slot 10: i2c_write_stretch.asm
            12'ha00: word = 16'h8007;  //   0  CONFIG open_drain01, 3
            12'ha01: word = 16'h8001;  //   1  CONFIG shift_dir, 1
            12'ha02: word = 16'h4380;  //   2  PULL 0, 0 [3]
            12'ha03: word = 16'h01a0;  //   3  SET 1, 0 [1]
            12'ha04: word = 16'h2100;  //   4  SHIFT_OUT  [1]
            12'ha05: word = 16'h00b0;  //   5  SET 1, 1
            12'ha06: word = 16'ha205;  //   6  WAIT 1, 1 [2]
            12'ha07: word = 16'h01a0;  //   7  SET 1, 0 [1]
            12'ha08: word = 16'h2100;  //   8  SHIFT_OUT  [1]
            12'ha09: word = 16'h00b0;  //   9  SET 1, 1
            12'ha0a: word = 16'ha205;  //  10  WAIT 1, 1 [2]
            12'ha0b: word = 16'h01a0;  //  11  SET 1, 0 [1]
            12'ha0c: word = 16'h2100;  //  12  SHIFT_OUT  [1]
            12'ha0d: word = 16'h00b0;  //  13  SET 1, 1
            12'ha0e: word = 16'ha205;  //  14  WAIT 1, 1 [2]
            12'ha0f: word = 16'h01a0;  //  15  SET 1, 0 [1]
            12'ha10: word = 16'h2100;  //  16  SHIFT_OUT  [1]
            12'ha11: word = 16'h00b0;  //  17  SET 1, 1
            12'ha12: word = 16'ha205;  //  18  WAIT 1, 1 [2]
            12'ha13: word = 16'h01a0;  //  19  SET 1, 0 [1]
            12'ha14: word = 16'h2100;  //  20  SHIFT_OUT  [1]
            12'ha15: word = 16'h00b0;  //  21  SET 1, 1
            12'ha16: word = 16'ha205;  //  22  WAIT 1, 1 [2]
            12'ha17: word = 16'h01a0;  //  23  SET 1, 0 [1]
            12'ha18: word = 16'h2100;  //  24  SHIFT_OUT  [1]
            12'ha19: word = 16'h00b0;  //  25  SET 1, 1
            12'ha1a: word = 16'ha205;  //  26  WAIT 1, 1 [2]
            12'ha1b: word = 16'h01a0;  //  27  SET 1, 0 [1]
            12'ha1c: word = 16'h2100;  //  28  SHIFT_OUT  [1]
            12'ha1d: word = 16'h00b0;  //  29  SET 1, 1
            12'ha1e: word = 16'ha205;  //  30  WAIT 1, 1 [2]
            12'ha1f: word = 16'h01a0;  //  31  SET 1, 0 [1]
            12'ha20: word = 16'h2100;  //  32  SHIFT_OUT  [1]
            12'ha21: word = 16'h00b0;  //  33  SET 1, 1
            12'ha22: word = 16'ha205;  //  34  WAIT 1, 1 [2]
            12'ha23: word = 16'h01a0;  //  35  SET 1, 0 [1]
            12'ha24: word = 16'h0190;  //  36  SET 0, 1 [1]
            12'ha25: word = 16'h00b0;  //  37  SET 1, 1
            12'ha26: word = 16'ha005;  //  38  WAIT 1, 1
            12'ha27: word = 16'h2102;  //  39  SHIFT_IN 0 [1]
            12'ha28: word = 16'h41a1;  //  40  PUSH 1, 0 [1]
            12'ha29: word = 16'h0180;  //  41  SET 0, 0 [1]
            12'ha2a: word = 16'h00b0;  //  42  SET 1, 1
            12'ha2b: word = 16'ha005;  //  43  WAIT 1, 1
            12'ha2c: word = 16'h0390;  //  44  SET 0, 1 [3]
            // slot 11: i2c_write_addr_data.asm
            12'hb00: word = 16'h8007;  //   0  CONFIG open_drain01, 3
            12'hb01: word = 16'h8001;  //   1  CONFIG shift_dir, 1
            12'hb02: word = 16'h4380;  //   2  PULL 0, 0 [3]
            12'hb03: word = 16'h01a0;  //   3  SET 1, 0 [1]
            12'hb04: word = 16'h2100;  //   4  SHIFT_OUT  [1]
            12'hb05: word = 16'h03b0;  //   5  SET 1, 1 [3]
            12'hb06: word = 16'h01a0;  //   6  SET 1, 0 [1]
            12'hb07: word = 16'h2100;  //   7  SHIFT_OUT  [1]
            12'hb08: word = 16'h03b0;  //   8  SET 1, 1 [3]
            12'hb09: word = 16'h01a0;  //   9  SET 1, 0 [1]
            12'hb0a: word = 16'h2100;  //  10  SHIFT_OUT  [1]
            12'hb0b: word = 16'h03b0;  //  11  SET 1, 1 [3]
            12'hb0c: word = 16'h01a0;  //  12  SET 1, 0 [1]
            12'hb0d: word = 16'h2100;  //  13  SHIFT_OUT  [1]
            12'hb0e: word = 16'h03b0;  //  14  SET 1, 1 [3]
            12'hb0f: word = 16'h01a0;  //  15  SET 1, 0 [1]
            12'hb10: word = 16'h2100;  //  16  SHIFT_OUT  [1]
            12'hb11: word = 16'h03b0;  //  17  SET 1, 1 [3]
            12'hb12: word = 16'h01a0;  //  18  SET 1, 0 [1]
            12'hb13: word = 16'h2100;  //  19  SHIFT_OUT  [1]
            12'hb14: word = 16'h03b0;  //  20  SET 1, 1 [3]
            12'hb15: word = 16'h01a0;  //  21  SET 1, 0 [1]
            12'hb16: word = 16'h2100;  //  22  SHIFT_OUT  [1]
            12'hb17: word = 16'h03b0;  //  23  SET 1, 1 [3]
            12'hb18: word = 16'h01a0;  //  24  SET 1, 0 [1]
            12'hb19: word = 16'h2100;  //  25  SHIFT_OUT  [1]
            12'hb1a: word = 16'h03b0;  //  26  SET 1, 1 [3]
            12'hb1b: word = 16'h01a0;  //  27  SET 1, 0 [1]
            12'hb1c: word = 16'h0190;  //  28  SET 0, 1 [1]
            12'hb1d: word = 16'h23b2;  //  29  SHIFT_IN 0, 1, 1 [3]
            12'hb1e: word = 16'h40a1;  //  30  PUSH 1, 0
            12'hb1f: word = 16'hc000;  //  31  SKIP 0, 0
            12'hb20: word = 16'h603d;  //  32  JMP 61
            12'hb21: word = 16'h4100;  //  33  PULL  [1]
            12'hb22: word = 16'h2100;  //  34  SHIFT_OUT  [1]
            12'hb23: word = 16'h03b0;  //  35  SET 1, 1 [3]
            12'hb24: word = 16'h01a0;  //  36  SET 1, 0 [1]
            12'hb25: word = 16'h2100;  //  37  SHIFT_OUT  [1]
            12'hb26: word = 16'h03b0;  //  38  SET 1, 1 [3]
            12'hb27: word = 16'h01a0;  //  39  SET 1, 0 [1]
            12'hb28: word = 16'h2100;  //  40  SHIFT_OUT  [1]
            12'hb29: word = 16'h03b0;  //  41  SET 1, 1 [3]
            12'hb2a: word = 16'h01a0;  //  42  SET 1, 0 [1]
            12'hb2b: word = 16'h2100;  //  43  SHIFT_OUT  [1]
            12'hb2c: word = 16'h03b0;  //  44  SET 1, 1 [3]
            12'hb2d: word = 16'h01a0;  //  45  SET 1, 0 [1]
            12'hb2e: word = 16'h2100;  //  46  SHIFT_OUT  [1]
            12'hb2f: word = 16'h03b0;  //  47  SET 1, 1 [3]
            12'hb30: word = 16'h01a0;  //  48  SET 1, 0 [1]
            12'hb31: word = 16'h2100;  //  49  SHIFT_OUT  [1]
            12'hb32: word = 16'h03b0;  //  50  SET 1, 1 [3]
            12'hb33: word = 16'h01a0;  //  51  SET 1, 0 [1]
            12'hb34: word = 16'h2100;  //  52  SHIFT_OUT  [1]
            12'hb35: word = 16'h03b0;  //  53  SET 1, 1 [3]
            12'hb36: word = 16'h01a0;  //  54  SET 1, 0 [1]
            12'hb37: word = 16'h2100;  //  55  SHIFT_OUT  [1]
            12'hb38: word = 16'h03b0;  //  56  SET 1, 1 [3]
            12'hb39: word = 16'h01a0;  //  57  SET 1, 0 [1]
            12'hb3a: word = 16'h0190;  //  58  SET 0, 1 [1]
            12'hb3b: word = 16'h23b2;  //  59  SHIFT_IN 0, 1, 1 [3]
            12'hb3c: word = 16'h41a1;  //  60  PUSH 1, 0 [1]
            12'hb3d: word = 16'h0180;  //  61  SET 0, 0 [1]
            12'hb3e: word = 16'h01b0;  //  62  SET 1, 1 [1]
            12'hb3f: word = 16'h0390;  //  63  SET 0, 1 [3]
            default: word = 16'h0000;
        endcase

        case (sel)
            4'd1: words = 9'd11;
            4'd2: words = 9'd11;
            4'd3: words = 9'd12;
            4'd4: words = 9'd12;
            4'd5: words = 9'd21;
            4'd6: words = 9'd21;
            4'd7: words = 9'd22;
            4'd8: words = 9'd22;
            4'd9: words = 9'd34;
            4'd10: words = 9'd45;
            4'd11: words = 9'd64;
            default: words = 9'd0;
        endcase
    end

endmodule
