"""Generate rtl/rom.v, the on-chip program ROM, from programs/manifest.txt.

    python tools/gen_rom.py            # writes rtl/rom.v
    python tools/gen_rom.py --check    # exit 1 if rtl/rom.v is not what it would write

One ROM per slot, looked up by {sel, addr}: every program keeps its own
addresses from 0, so absolute JMP targets need no relocation. Slot 0 and any
slot the manifest does not name read word 0 and words 0, which halts the core.
Deterministic: same manifest and programs, byte-identical output.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "model"))

from cpu import decode, load_isa, load_program  # noqa: E402

MANIFEST = ROOT / "programs" / "manifest.txt"
OUT = ROOT / "rtl" / "rom.v"
SEL_BITS = 4
ADDR_BITS = 8
WORDS_BITS = 9


def read_manifest(path=MANIFEST):
    """{slot: file name}. Slots 1..2**SEL_BITS-1, each once, files in programs/."""
    slots = {}
    for lineno, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        try:
            slot, name = line.split()
            slot = int(slot)
        except ValueError:
            raise ValueError(f"{path.name} line {lineno}: expected 'slot file', got {raw!r}") from None
        if not 1 <= slot < (1 << SEL_BITS):
            raise ValueError(f"{path.name} line {lineno}: slot {slot} outside 1..{(1 << SEL_BITS) - 1}")
        if slot in slots:
            raise ValueError(f"{path.name} line {lineno}: slot {slot} given twice")
        slots[slot] = name
    return slots


def listing(word, isa):
    """One word back as assembly, for the comment beside it: the instruction's
    own operands (a CONFIG field by name), then the side effect, then the delay."""
    i = decode(word, isa)
    args = list(i.args)
    if i.op == "CONFIG":
        names = {v["field"]: k for k, v in isa["config"].items()}
        args[0] = names.get(args[0], args[0])
    operands = ", ".join(str(a) for a in args + list(i.side or ()))
    delay = f" [{i.delay}]" if i.delay else ""
    return f"{i.op} {operands}{delay}".rstrip()


def render(slots, programs, isa=None):
    """Verilog for `rom` from {slot: name} and {slot: [words]}."""
    isa = isa or load_isa()
    out = [
        "// Program ROM, GENERATED by tools/gen_rom.py from programs/manifest.txt. Do not edit;",
        "// run `make rom` after changing a program or the manifest, `make rom-check` guards it.",
        "//",
        "// One ROM per slot: word = program[sel][addr], words = its length. Slot 0 and every",
        "// slot not listed read 0 and 0, so the core halts. Programs keep their own addresses.",
        "//",
        "// slot  words  program",
    ]
    for slot in sorted(slots):
        out.append(f"//   {slot:2d}    {len(programs[slot]):3d}  {Path(slots[slot]).name}")
    out += [
        "",
        "module rom (",
        f"    input      [{SEL_BITS - 1}:0]  sel,",
        f"    input      [{ADDR_BITS - 1}:0]  addr,",
        "    output reg [15:0] word,",
        f"    output reg [{WORDS_BITS - 1}:0]  words",
        ");",
        "",
        "    always @* begin",
        "        case ({sel, addr})",
    ]
    for slot in sorted(slots):
        out.append(f"            // slot {slot}: {Path(slots[slot]).name}")
        for addr, word in enumerate(programs[slot]):
            out.append(
                f"            {SEL_BITS + ADDR_BITS}'h{(slot << ADDR_BITS) | addr:03x}: word = 16'h{word:04x};"
                f"  // {addr:3d}  {listing(word, isa)}"
            )
    out += [
        "            default: word = 16'h0000;",
        "        endcase",
        "",
        "        case (sel)",
    ]
    for slot in sorted(slots):
        out.append(f"            {SEL_BITS}'d{slot}: words = {WORDS_BITS}'d{len(programs[slot])};")
    out += [
        f"            default: words = {WORDS_BITS}'d0;",
        "        endcase",
        "    end",
        "",
        "endmodule",
        "",
    ]
    return "\n".join(out)


def generate(manifest=MANIFEST):
    slots = read_manifest(manifest)
    programs = {slot: load_program(manifest.parent / name) for slot, name in slots.items()}
    for slot, words in programs.items():
        if len(words) > (1 << ADDR_BITS):
            raise ValueError(f"slot {slot}: {len(words)} words, more than {1 << ADDR_BITS}")
    return render(slots, programs)


def main(argv):
    text = generate()
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run `make rom`", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
